<div data-v-7b003a97="" id="wikiContent" class="article-content"><h1 id="header-0"><a id="_0"></a><strong>通知栏消息</strong></h1>
<table>
<thead>
<tr>
<th>名称</th>
<th>类型</th>
<th>是否必填</th>
<th>默认</th>
<th>描述</th>
<th>是否支持单推</th>
</tr>
</thead>
<tbody>
<tr>
<td>app_message_id</td>
<td>String</td>
<td>否</td>
<td>无</td>
<td>App开发者自定义消息Id，主要用于消息去重。<br>对于广播消息，相同app_message_id只会保存一条；<br>对于单推消息，相同app_message_id的消息只会对同一个目标推送一次。</td>
<td>是</td>
</tr>
<tr>
<td>style</td>
<td>Int</td>
<td>否</td>
<td>1</td>
<td>通知栏样式<br>1. 标准样式<br>2. 长文本样式<br>（ColorOS版本&gt;5.0可用，通知栏第一条消息可展示全部内容，非第一条消息只展示一行内容）<br>3. 大图样式<br>（ColorOS版本&gt;5.0可用，通知栏第一条消息展示大图，非第一条消息不显示大图，推送方式仅支持广播，且不支持定速功能）。</td>
<td>是</td>
</tr>
<tr>
<td>big_picture_id</td>
<td>String</td>
<td>否</td>
<td>无</td>
<td>大图id【style为3时，必填】,通过上传大图接口获得大图id后可使用。<br>上传大图接口请参考服务端API介绍章节</td>
<td>否</td>
</tr>
<tr>
<td>small_picture_id</td>
<td>String</td>
<td>否</td>
<td>无</td>
<td>通知图标id,通过上传小图接口获得小图id后可使用。<br>上传小图接口请参考服务端API介绍章节。</td>
<td>否</td>
</tr>
<tr>
<td>title</td>
<td>String</td>
<td>是</td>
<td>无</td>
<td>设置在通知栏展示的通知栏标题, 【字数串长度限制在50个字符内，中英文字符及特殊符号（如emoji）均视为一个字符】</td>
<td>是</td>
</tr>
<tr>
<td>sub_title</td>
<td>String</td>
<td>否</td>
<td>无</td>
<td>子标题，设置在通知栏展示的通知栏标题, 【字符串长度限制在10个字符以内，中英文字符及特殊符号（如emoji）均视为一个字符计算】</td>
<td>是</td>
</tr>
<tr>
<td>content</td>
<td>String</td>
<td>是</td>
<td>无</td>
<td>设置在通知栏展示的通知的正文内容<br>1）当选择标准样式（style 设置为 1）时，内容字符串长度限制在50以内；<br>2）当选择长文本样式（style设置 为 2）时，内容字符串长度限制在128以内；<br>3）当选择大图样式（style 设置为 3）时，内容字符串长度限制在50以内。<br>【字符串长度计算说明：中英文字符及特殊符号（如emoji）均视作一个字符计算】</td>
<td>是</td>
</tr>
<tr>
<td>click_action_type</td>
<td>Int</td>
<td>否</td>
<td>0</td>
<td>点击通知栏后触发的动作类型。<br>点击动作类型值的定义和含义如下：<br>0.启动应用；<br>1.跳转指定应用内页（action标签名）；<br>2.跳转网页；<br>4.跳转指定应用内页（全路径类名）；【非必填，默认值为0】;<br>5.跳转Intent scheme URL</td>
<td>是</td>
</tr>
<tr>
<td>click_action_activity</td>
<td>String</td>
<td>否</td>
<td>Null</td>
<td>当设置click_action_type为1或者4时，需要配置本参数。<br>应用内页地址【click_action_type为1/4/时必填，长度500】<br>示例：<br>假设应用注册了类名为InternalActivity的activity，应用内页的xml配置如下<br><img src="https://openfs.oppomobile.com/open/res/202206/02/41da830ced40b7f388bbfb61a2ca2849.png" alt="image.png"><br>当开发者期望消息被点击后跳转到这个应用内页，可以有两种方法传递参数：<br>指定click_action_type为1时，click_action_activity传入com.coloros.push.demo.internal<br>指定click_action_type为4时，click_action_activity传入com.coloros.push.demo.component.InternalActivity</td>
<td>是</td>
</tr>
<tr>
<td>click_action_url</td>
<td>String</td>
<td>否</td>
<td>Null</td>
<td>跳转URL，当跳转的形式为URL时，click_action_type参数需要设置为2或5，同时设置本参数。本参数接受最大长度2000以内的URL。<br>示例：<br>click_action_type为2时，本参数可设置为<a href="http://oppo.com/?key1=val1&amp;key2=val2" target="_blank">http://oppo.com?key1=val1&amp;key2=val2</a><br>click_action_type为5时，本参数可设置为command://test?key1=val1&amp;key2=val2</td>
<td>是</td>
</tr>
<tr>
<td>action_parameters</td>
<td>String</td>
<td>否</td>
<td>Null</td>
<td>跳转动作参数。<br>打开应用内页或网页时传递给应用或网页的附加参数【JSON格式】，字符串长度不超过4000。当跳转类型是URL类型时，参数会以URL参数直接拼接在URL后面。<br>示例：{“key1”:“value1”,“key2”:“value2”}</td>
<td>是</td>
</tr>
<tr>
<td>show_time_type</td>
<td>Int</td>
<td>否</td>
<td>0</td>
<td>通知栏展示类型。展示类型如下<br>0：即时展示<br>1：定时展示，配置该参数后定时展示开始时间（show_start_time）及定时展示的结束时间（show_end_time）为必填</td>
<td>是</td>
</tr>
<tr>
<td>show_start_time</td>
<td>Long</td>
<td>是</td>
<td>0</td>
<td>定时展示的开始时间。<br>选择定时展示后，消息将于设定的开始时间到结束时间之内展示，展示开始时间不能大于等于展示结束时间。<br>本参数接受13位的unix时间戳。</td>
<td>是</td>
</tr>
<tr>
<td>show_end_time</td>
<td>Long</td>
<td>是</td>
<td>0</td>
<td>定时展示的结束时间。<br>选择定时展示后，消息将于设定的开始时间到结束时间之内展示。<br>本参数接受13位的unix时间戳。</td>
<td>是</td>
</tr>
<tr>
<td>off_line</td>
<td>Boolean</td>
<td>否</td>
<td>TRUE</td>
<td>是否是离线消息。<br>如果是离线消息，OPPO PUSH在设备离线期间缓存消息一段时间，等待设备上线接收。</td>
<td>是</td>
</tr>
<tr>
<td>off_line_ttl</td>
<td>Int</td>
<td>否</td>
<td>3600</td>
<td>离线消息的存活时间，单位是秒。存活时间最大允许设置为10天，参数超过10天以10天传入。</td>
<td>是</td>
</tr>
<tr>
<td>push_time_type</td>
<td>Int</td>
<td>否</td>
<td>0</td>
<td>定时推送 (0, “即时”),(1, “定时”), 【只对全部用户推送生效】</td>
<td>否</td>
</tr>
<tr>
<td>push_start_time</td>
<td>Long</td>
<td>否</td>
<td>0</td>
<td>定时推送开始时间（根据time_zone转换成当地时间）, 【push_time_type 为1必填】，时间的毫秒数</td>
<td>否</td>
</tr>
<tr>
<td>time_zone</td>
<td>String</td>
<td>否</td>
<td>GMT+08:00</td>
<td>时区，默认值：（GMT+08:00）北京，香港，新加坡</td>
<td>是</td>
</tr>
<tr>
<td>fix_speed</td>
<td>Boolean</td>
<td>否</td>
<td>FALSE</td>
<td>是否定速推送。广播类型消息专用，如果设置定速推送，消息将会以给定的速度均匀下发。</td>
<td>否</td>
</tr>
<tr>
<td>fix_speed_rate</td>
<td>Long</td>
<td>否</td>
<td>1000</td>
<td>定速推送的速率，单位为条每秒。 <br>指定消息为定速推送消息时，需要指定本参数。<br>定速推送速率范围在[1000, 10000]。</td>
<td>否</td>
</tr>
<tr>
<td>network_type</td>
<td>Int</td>
<td>否</td>
<td>0</td>
<td>推送的网络环境类型。<br>本参数将影响用户设备仅在指定类型的网络环境下接收消息。<br>参数定义如下：<br>0：不限联网方式；<br>1：仅wifi推送，设置后，消息只会在用户处于WiFi环境下才下发。</td>
<td>否</td>
</tr>
<tr>
<td>call_back_url</td>
<td>String</td>
<td>否</td>
<td>无</td>
<td>回执功能详见<a href="https://open.oppomobile.com/new/developmentDoc/info?id=11239" target="_blank">回执</a>一章<em>仅支持registrationId推送方式</em>开发者接收消息送达的回执消息的URL地址。<br>OPPO PUSH提供消息回执的功能，消息回执的功能是指消息送达后，OPPO PUSH基于HTTP/HTTPS请求的方式告知开发者对应消息的送达情况。<br>要使用回执功能，开发者需要配置回执目标地址的URL参数，URL长度限制在限制200以内。<br>以下是一个使用回执的示例：<br>1.开发者配置本参数<br>2.消息到达设备后，OPPO PUSH根据本参数，向这个URL以Content-Type为application/json的方式发送一个HTTP/HTTPS请求。<br><br>请求内容的示例如下JSON 数据示例：<br>[<br> {<br>   “messageId”: “msgId1”, // 到达的消息ID  <br>   “appId”: “appid”, // 对应的应用ID  <br>   “taskId”: “taskId1”, // 如果是广播消息，对应taskID；如果是单推消息，该字段为消息ID       <br>    “registrationIds”: “regId1, regid2”, // 消息的推送目标注册ID  <br>    “eventTime”: “timestamp”, // 回执事件产生时间  <br>    “param”: “call_back_parameter”, // 开发者指定的回执参数  <br>    “eventType”: “push_arrive” // 到达事件，消息到达的事件被定义为push_arrive<br>    },<br>    // 对于完全一致的URL地址，OPPO PUSH可能会将相同URL地址回执信息在一个HTTP/HTTPS请求中发送,因此body里是一个长度大于等于1的JSON数组 <br>       {  “messageId”: “msgId1”,  <br>          “appId”: “appid”,  <br>          “taskId”: “taskId1”,  <br>          “registrationIds”: “regId1,regid2”,  <br>          “eventTime”: “timestamp”,  <br>          “param”: “call_back_parameter”,  <br>           “eventType”: “push_arrive”<br>        }<br>]</td>
<td>是</td>
</tr>
<tr>
<td>call_back_parameter</td>
<td>String</td>
<td>否</td>
<td>无</td>
<td>开发者指定的自定义回执参数。<br>参数字符串长度限制在100以内，OPPO PUSH将这个参数设置在回执请求体单个JSON结构的param字段中。</td>
<td>是</td>
</tr>
<tr>
<td>channel_id</td>
<td>String</td>
<td>否</td>
<td>OPPO PUSH 提供的默认通道ID</td>
<td>指定下发的通道ID。<br>通知栏通道（NotificationChannel），从Android9开始，Android设备发送通知栏消息必须要指定通道ID，（如果是快应用，必须带置顶的通道Id:OPPO PUSH推送）</td>
<td>是</td>
</tr>
<tr>
<td>show_ttl</td>
<td>Int</td>
<td>否</td>
<td>公信43200<br>私信86400</td>
<td>限时展示时间(单位：秒)。<br>消息在通知栏展示后开始计时，展示时长超过展示事件后，消息会从通知栏中消失。<br>限时展示的时间范围：公信0-12小时，私信0-24小时。</td>
<td>是</td>
</tr>
<tr>
<td>notify_id</td>
<td>Int</td>
<td>否</td>
<td>由OPPO PUSH生成</td>
<td>每条消息在通知显示时的唯一标识，主要用于新旧消息的覆盖。不设置本参数时，PUSH自动为给每条消息生成一个唯一标识；<br>当不同的消息设置为同一个notify_id，到达设备的新消息将覆盖旧消息展示在设备通知栏中。</td>
<td>是</td>
</tr>
<tr>
<td>auditResponse</td>
<td>JSON</td>
<td>否</td>
<td>null</td>
<td>推必安信息审核api响应内容，详见<a href="https://open.oppomobile.com/new/developmentDoc/info?id=11344" target="_blank">《基于第三方审核结果的消息推送》</a></td>
<td>是</td>
</tr>
<tr>
<td>category</td>
<td>String</td>
<td>否</td>
<td>无</td>
<td>通道类别名，详见<a href="https://open.oppomobile.com/new/developmentDoc/info?id=13189" target="_blank">《新消息分类场景说明》</a></td>
<td>是</td>
</tr>
<tr>
<td>notify_level</td>
<td>Int</td>
<td>否</td>
<td>2</td>
<td>通知栏消息提醒等级取值定义<br>1-通知栏<br>2-通知栏+锁屏<br>16-通知栏+锁屏+横幅+震动+铃声<br>使用notify_level参数时，category参数必传</td>
<td>是</td>
</tr>
</tbody>
</table>
</div>